# -*- coding: utf-8 -*-
"""linear_regression_housing_area_price.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NnceqyRhhy_g-XpAgOtGoLjGeRglmbM-
"""

import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

df=pd.read_csv("/content/canada_per_capita_income.csv")
df

plt.xlabel('year')
plt.ylabel('income')
plt.scatter(df.year,df.percapitaincome,color='red',marker='+')
new_df = df.drop('percapitaincome',axis='columns')
percapitaincome=df['percapitaincome']

reg=linear_model.LinearRegression()
reg.fit(new_df,percapitaincome)
print(reg.coef_)
reg.intercept_

y=828.46507522*2020+-1632210.7578554575
print(y)
reg.predict([[2020]])

import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

df=pd.read_csv("/content/salary.csv")
df.isnull().sum()
df=df.fillna({"YearsExperience":df['YearsExperience'].mean()})
df.isnull().sum()
plt.xlabel('YearsExperience')
plt.ylabel('Salary')
plt.scatter(df.YearsExperience,df.Salary,color='red',marker='+')

reg=linear_model.LinearRegression()
new_df=df.drop("Salary",axis="columns")
salery=df["Salary"]
reg.fit(new_df,salery)
# print(reg.coef_)
# reg.intercept_
print(reg.predict([[12]]))

import pandas as pd
import numpy as np
from sklearn import linear_model


df = pd.read_csv("/content/hiring.csv")


df['experience'] = df['experience'].bfill()
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(df['test_score(out of 10)'].mean())

text_to_num = {
    'zero': 0, 'one': 1, 'two': 2, 'three': 3, 'four': 4,
    'five': 5, 'six': 6, 'seven': 7, 'eight': 8, 'nine': 9,
    'ten': 10, 'eleven': 11, 'twelve': 12
}
df['experience'] = df['experience'].map(text_to_num)


new_df = df.drop("salary", axis="columns")
salary = df['salary']


reg = linear_model.LinearRegression()
reg.fit(new_df, salary)

print(reg.predict([[2, 9, 6]]))
print(reg.predict([[12, 10, 10]]))

import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.preprocessing import OrdinalEncoder

df = pd.read_csv("/content/1000_Companies.csv")

ordinal_encoder = OrdinalEncoder(categories=[["New York", "California","Florida"]])
# Fit and transform the data
df["State"] = ordinal_encoder.fit_transform(df[["State"]])


new_df = df.drop("Profit", axis="columns")
profit = df['Profit']

df.head()
reg = linear_model.LinearRegression()
reg.fit(new_df, profit)

reg.predict([[91694.48,515841.3,11931.24,2]])